version: '3'
services:

  console:
    build: .
    links:
      - db
    depends_on:
      - db
    command: tail -F anything


  api:
    build: api/.
    ports:
      - "5000:5000"
    links:
      - db
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hbnb_dev_db
      MYSQL_USER: hbnb_dev
      MYSQL_PASSWORD: hbnb_dev_pwd

volumes:
   db_data:
