#!/usr/bin/python3
"""Creates endpoint"""
from api.v1.views import app_views
from flask import jsonify
from models import storage

@app_views.route('/stats', methodsi=['GET'])
def get_stats():
    """Get the number of objects by type"""
    types_to_count = {
        'Amenity': storage.count('Amenity'),
        'City': storage.count('City'),
        'Place': storage.count('Place'),
        'Review': storage.count('Review'),
        'State': storage.count('State'),
        'User': storage.count('User'),
    }
    return jsonify(types_to_count)
